package csx55.overlay.wireformats;

public enum Protocol {
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    DEREGISTER_REQUEST,
    DEREGISTER_RESPONSE,
    MESSAGING_NODES_LIST,
    LINK_WEIGHTS,
    TASK_INITIATE,
    TASK_COMPLETE,
    FULL_TRAFFIC_SUMMARY,
    TRAFFIC_SUMMARY
}
